services:
  - type: web
    name: sandra-task-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: REPLACE_WITH_REAL_MONGODB_URI
      - key: JWT_SECRET
        value: Sandra2025